import React from 'react';

const TermsOfUse = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 py-8">
      <h1 className="text-2xl font-bold text-left mb-6">
        Computer Agent Arena Terms of Use
      </h1>
      <div 
        className="bg-gray-100 rounded-lg overflow-y-auto px-6 py-4 font-['Times_New_Roman'] dark:bg-gray-800 dark:text-white"
      >
        <h2 className="text-xl font-bold mb-4">Terms of Service</h2>
        <p className="text-base mb-4">By using this service, you agree to:</p>
        
        <ul className="list-disc pl-8 space-y-4">
          <li className="text-base leading-relaxed">
            <strong>Access:</strong> You will receive two OSWorld virtual machines, each paired with an anonymized agent.
          </li>
          
          <li className="text-base leading-relaxed">
            <strong>Data Collection:</strong> We collect and may share your task instructions, computer control actions, screenshots, and accessibility data. We reserve the right to distribute them under a Creative Commons Attribution (CC-BY) or a similar license. Do not include personal information you wish to keep private.
          </li>
          
          <li className="text-base leading-relaxed">
            <strong>Usage Rights:</strong> VMs are for research purposes only. Users have limited usage rights, not ownership. Any illegal, personal, or commercial use is prohibited and may result in account termination and legal action.
          </li>
          
          <li className="text-base leading-relaxed">
            <strong>Safety & Content:</strong> The service provides basic safety measures only and may generate offensive content. Use for illegal, harmful, violent, racist, or sexual purposes is strictly forbidden. Users are advised to use discretion and judgment when interacting with the agent model. Arena is not responsible for any content or results generated by the AI agent or submitted by users.

          </li>
          
          <li className="text-base leading-relaxed">
            <strong>Evaluation:</strong> Users must provide fair, unbiased agent evaluations for research. Unreasonable evaluations may lead to restricted access.
          </li>
          <li className="text-base leading-relaxed">
            <strong>Changes to terms:</strong> We reserve the right to modify or replace these terms at any time. It is your responsibility to check the Terms periodically for changes.
          </li>
        </ul>

        <p className="text-base mt-8">
          By using the Computer Agent Arena service, you acknowledge that you have read, understood, and agree to these terms. We reserve the right to update these terms at any time, and your continued use of the service constitutes acceptance of any changes.
        </p>
      </div>
    </div>
  );
};

export default TermsOfUse; 